apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rke2-security-responder.labels" . | nindent 4 }}
